apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: saf-next-boilerplate
  title: Web Portal Starter
  description: Create a simple web portal starter using React and NextJS
  tags:
    - recommended
    - javascript
    - nextjs
    - react
spec:
  owner: WebSquad@Safaricom.co.ke
  type: service

  parameters:
    - title: Provide some simple information
      required:
        - owner
        - portal_name
      properties:
        portal_name:
          title: Portal Name
          type: string 
          description: Name for the portal. eg (sim-portal*)
        description:
          title: Description
          type: string
          description: Help others understand what this service is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.safaricom.co.ke
              - 10.184.7.135:8090

  steps:
    - id: template
      name: Fetch Template
      action: fetch:template
      input:
        url: ./template
        copyWithoutTemplating:
          - .gitlab/workflows/*
        values:
          description: ${{ parameters.description }}
          portal_name: ${{ parameters.portal_name }}
          owner: ${{ parameters.owner }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ["gitlab.safaricom.co.ke","10.184.7.135:8090"]
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: dev

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
